### ISSUE TITLE
Recommendation on how to make the store immutable

### ISSUE THREAD

**Issue by knaeckeKami** [marcglasberg/async_redux#1]
Hi,
great library, I think I will use this!

I have one question: In your examples, you make the store immutable by declaring every variable final, implementing hashcode and ==, and providing a copy() method. That's fine, but for a bigger store that's a lot of boilerplate and can lead to mistakes.

Do you recommend using built_value or something similar for the store? Would this have any negative side effects?

**Comment by marcglasberg** [comment]
Ok, we have already discussed that in Slack, right? But I will soon add a section to the documentation with recommendations for keeping the store immutable, and why it needs to be immutable at all. I have already added two new sections yesterday, to explain how to interact with the database, and best practices to use Streams with AsyncRedux.

**Comment by knaeckeKami** [comment]
Yes, I closed the issue after our discussion on slack.
