### ISSUE TITLE
Compatibility with integration_test

### ISSUE THREAD

**Issue by VincentMichuki** [marcglasberg/async_redux#102]
I am getting this when I use latest  async_redux version and flutter 2.0 and integration ^1.0.2+2.

`Because every version of integration_test depends on flutter_driver any from sdk which depends on file 6.0.0, every version of integration_test requires file 6.0.0.

    | And because async_redux 9.0.0 depends on file ^6.1.0 and no versions of async_redux match >9.0.0 <10.0.0, integration_test is incompatible with async_redux ^9.0.0.

    | So, because <MyApp> depends on both async_redux ^9.0.0 and integration_test ^1.0.2+2, version solving failed`

**Comment by marcglasberg** [comment]
@VincentMichuki Could you please test if version **9.0.1** solves this?

**Comment by VincentMichuki** [comment]
Yes it does. Thank you for the quick fix and response.
