### ISSUE TITLE
before() swallows reducer() errors

### ISSUE THREAD

**Issue by abijr** [marcglasberg/async_redux#105]
I expect for the error thrown in the reducer to get wrapped by the `wrapError` method regardless of the `before` override presence.

Full example derived from the main_before_and_after.dart example: https://gist.github.com/abijr/f33e93d9282b006fb1299b157152c9cf

If you comment the [before override](https://gist.github.com/abijr/f33e93d9282b006fb1299b157152c9cf#file-bad_before-dart-L101-L102) the error dialog appears. But if left uncommented, the reducer fails silently.

Additional notes:
* This only happens if I dispatch something in the `before()` override.
* Errors get handled by the wrapError override in the action dispatched in `before`, even if the exception is thrown in the reducer.

Maybe I'm missing something.

Thanks for the awesome library!

**Comment by abijr** [comment]
Found a workaround.

If I dispatch the actions with the `notify: false` option, I can get my error dialogs to appear.

But it removes the effect of `barrier` type actions dispatched in the before method.

**Comment by marcglasberg** [comment]
This is fixed in version [13.0.0-dev0]:

  https://pub.dev/packages/async_redux/versions/13.0.0-dev

Please read the Changelog:

  https://pub.dev/packages/async_redux/versions/13.0.0-dev/changelog
