### ISSUE TITLE
Unable to test errors being thrown

### ISSUE THREAD

**Issue by Pitazzo** [marcglasberg/async_redux#114]
I'm trying to write a test to validate that an action throws an error under some conditions. In order to do so, I tried to use `waitUntilError(...)` method, but for now without success. As I also mentioned in #112, I don't know whether the method has a bug or I'm not using it as intended.

Given following action:
```
class CrashAction extends ReduxAction<AppState> {
  @override
  AppState reduce() {
    throw Exception();
  }
}
```

I wrote following test:
```
test('should throw Exception', () async {
  storeTester!.dispatch(CrashAction());
  await storeTester!.waitUntilError(error: Exception);
});
```

I expected this test to pass. However, to fails with following trace:
```
New StoreTester.
D:1 R:0 = Action CrashAction INI

D:1 R:1 = Action CrashAction END

Exception
CrashAction.reduce
package:controlcenter/…/actions/crash_action.dart:64
Store._applyReducer
package:async_redux/src/store.dart:369
Store._processAction
package:async_redux/src/store.dart:330
Store._dispatch
package:async_redux/src/store.dart:278
Store.dispatch
package:async_redux/src/store.dart:263
MockStore.dispatch
package:async_redux/src/mock_store.dart:82
StoreTester.dispatch
package:async_redux/src/store_tester.dart:131
main.<fn>.<fn>
test/…/actions/crash_action_test.dart:99
main.<fn>.<fn>
test/…/actions/crash_action_test.dart:98
===== asynchronous gap ===========================
dart:async                                                        _completeOnAsyncError
package:async_redux/src/store.dart                                Store._processAction
package:async_redux/src/store.dart:1
Store._dispatch
package:async_redux/src/store.dart:278
Store.dispatch
package:async_redux/src/store.dart:263
MockStore.dispatch
package:async_redux/src/mock_store.dart:82
StoreTester.dispatch
package:async_redux/src/store_tester.dart:131
main.<fn>.<fn>
test/…/actions/crash_action_test.dart:99
main.<fn>.<fn>
test/…/actions/crash_action_test.dart:98
2

✖ should throw Exception
Exited (1)

```

I also tried to change the value of `shouldThrowUserExceptions`, but result was the same.

**Comment by yamauchieduardo** [comment]
Hi @Pitazzo 👋

I'm use this method a lot and is working. The behavior act as a expected, the action throw a crash and the second-line in your code isn't executed.

The `AsyncRedux` and the `StoreTester` have some assumptions and is important how test the actions/state/errors/exceptions correctly.

1) The `Store` don't swallow errors, the `Store` just swallow `UserException` to turn that in a dialog.
 
2) Using `StoreTester` if you dispatch a `Action` that throw a `UserException` in a `test` the flux will stop .

But sometimes you can test if some if some `UserException` is throw in a specific scenario. For this case if you can use `shouldThrowUserExceptions` with `false`. If this condition happen the `StoreTester` will swallow `UserException` (not stoping the flux) to be tested.

In the documentation, we have:

> If shouldThrowUserExceptions is true, all errors will be thrown,  and not swallowed, including UserException. Use this in all tests that should throw no errors. Pass `shouldThrowUserExceptions` as false when you are testing code that should throw  UserExceptions. These exceptions will then silently go to the `errors` queue, where you can assert they exist with the right error messages.`

If you want to test if some `UserException` is throw using `shouldThrowUserExceptions`, you can write tests like that:

```dart
   var storeTester = StoreTester(
     initialState: null,
     shouldThrowUserExceptions: true,
   );

  // Dispatch the action.
   storeTester.dispatch(ThrowsUserExceptionAction());

  // Wait until the userException is throw.
  await storeTester.waitUntilError(error: const UserException("A UserException!"));
  // OR by type: `await storeTester.waitUntilError(error: UserException);`

  expect(storeTester.lastInfo.errors.single, const UserException("A UserException!"));
```

To test your example action you can write a test like these:

```dart
class CrashAction extends ReduxAction<AppState> {
  @override
  AppState reduce() {
    throw Exception();
  }
}
```

```dart
test('should throw Exception', () async {
    var storeTester = StoreTester(
       initialState: initialState...,
    );

    expect(
      () => storeTester.dispatch(CrashAction()),
      throwsA(Exception()),
    );
});
```

OR:

```dart
test('should throw Exception', () async {
    var storeTester = StoreTester(
       initialState: initialState...,
    );

    late Exception exceptionExcepted;

    try {
	storeTester.dispatch(CrashAction())
    } on Exception catch(exception) {
    	exceptionExcepted = exception;
    }

    expect(exceptionExpected, isA<Exception>());
});
```

OR:

```dart
test('should throw Exception', () async {
    var storeTester = StoreTester(
       initialState: initialState...,
    );

    try {
	storeTester.dispatch(CrashAction())
    } catch(e) {
    	// Ignore every object threw.
    }

    expect(storeTester.lastInfo.errors.single, isA<Exception>());
});
```

Hope this help!
