### ISSUE TITLE
Missing dispatchSync getter in VmFactory

### ISSUE THREAD

**Issue by swch01** [marcglasberg/async_redux#116]
The abstract class [`VmFactory`](https://github.com/marcglasberg/async_redux/blob/2df97033a8eb247b28f57e8e70074e461f35360e/lib/src/view_model.dart#L151) has getters for `dispatch` and `dispatchAsync`, but not for `dispatchSync`.

**Comment by marcglasberg** [comment]
Fixed in version 13.0.6. Thank you!
