### ISSUE TITLE
onDidChange should not be called when the widget is not mounted

### ISSUE THREAD

**Issue by saibotma** [marcglasberg/async_redux#124]
f294e6e9cad814fef2da6ecc447c8895d3a75094 implements that `context` gets passed to `onDidChange`. However this throws when the widget using `onDidChange` is unmounted, even when the callback passed to `onDidChange` does never use `context`.

It is obvious when you look at the implementation of the `context` getter:
```
BuildContext get context {
    assert(() {
      if (_element == null) {
        throw FlutterError(
          'This widget has been unmounted, so the State no longer has a context (and should be considered defunct). \n'
          'Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.',
        );
      }
      return true;
    }());
    return _element!;
  }
```

```
if ((widget.onDidChange != null) && (_latestModel != null)) {
    WidgetsBinding.instance!.addPostFrameCallback((_) {
        widget.onDidChange!(context, widget.store, _latestModel!);
    });
}
```

Why do we actually need to pass `context` to `onDidChange`? One could easily access it in the `onDidChange` on their own.
How are we supposed to use `onDidChange`?

**Comment by marcglasberg** [comment]
Thank you for your report. Flutter has been tightening a lot of asserts recently, failing where it previously did not. I'd guess this assert did not exist when I wrote that code (not sure). In any case, I now test it's mounted before getting the context. **Fixed in version: 15.0.0**
