### ISSUE TITLE
How to return something when an Action is done?

### ISSUE THREAD

**Issue by SunlightDave** [marcglasberg/async_redux#13]
The RefreshIndicator's onRefresh wants a Future<void> Function(), that returned Future must complete when the refresh operation is finished.

Before I would make the call to the API first and then when the response returns I would dispatch an (synchronous) Action and return null.

Now with ReduxAction that can reduce async, I move the API call inside the Action, but what would be the proper way to return something as soon as the Action is finished ?

```dart
StoreConnector<AppState, Overview>(
  converter: (store) => store.state.overview,
  builder: (context, overview) {
    return overview == null
      ? Center(child: CircularProgressIndicator())
      : RefreshIndicator(
        onRefresh: () {
          StoreProvider.of<AppState>(context, 'refresh').dispatch(GetOverview());
          return Future.delayed(Duration(seconds: 1));
          /// Before I did this:
          //return ApiService().getOverview().then((Overview ov) {
          //  StoreProvider.of<AppState>(context, 'refresh').dispatch(SetOverview(ov));
          //  return null;
          //}
        },
        child: ListView(...),
```

**Comment by SunlightDave** [comment]
Thank you for help (I first tried to solve this with Events).

On another note, I'm not quite sure if this not something I should do or not. 
Is it discouraged to dispatch Actions without putting them as Callbacks in a ViewModel?

If not, then a Function something like this in the StoreProvider would be great, to easily dispatch Actions:
```dart
static void dispatch<St>(BuildContext context, ReduxAction action, Object debug) {
  StoreProvider.of<St>(context, debug).dispatch(action);
}
```

**Comment by marcglasberg** [comment]
https://github.com/marcglasberg/async_redux/pull/16

**Comment by marcglasberg** [comment]
This is now live: version: 1.3.8.

**Comment by marcglasberg** [comment]
Are @SunlightBro and @SunlightDave the same person? I did some changes in main_dispatch_future.dart, (including changing the file name), but you are the author. If you want you can list yourself as the author in the top file comment.

**Comment by SunlightBro** [comment]
Yes same person,
just keep it the way its is.
