### ISSUE TITLE
async_redux and go_router

### ISSUE THREAD

**Issue by R4dix** [marcglasberg/async_redux#139]
Hi Marc, 
I am currently working on a project using async_redux and I want to use go_router in this project as well.
Using go_router you always need the current context for navigating. I got a workaround where I create my ViewModels with the context as parameter. But this seems not the best way to handle this. Because go_router is the preferred way of handling navigation from Google maybe it would be good to have a more elegant way of handling the navigation combining these two packages. I liked the async_redux way with a NavigationAction. Maybe these two things can be combined?

Best Reagrds
Simon

**Comment by marcglasberg** [comment]
How about this:

```
class MyConnector extends StatelessWidget {

  Widget build(BuildContext context) {
    return StoreConnector<AppState, _Vm>(
      vm: () => _Factory(this),
      builder: (context, vm) => MyWidget( ... );

...

class _Factory extends VmFactory<AppState, MyConnector > {
  _Factory(Widget widget) : super(widget);

  BuildContext get context => widget.context;

  _Vm fromStore() {
    return _Vm(
      onNavigate: () {
         // Now you have access to the context here.
      }
  }
```

**Comment by R4dix** [comment]
Yes, this is exactly the way I am doing it right now. I was hoping there is a better way of doing this with an action.

**Comment by marcglasberg** [comment]
It's unclear to me what you mean by "better". I think the above way of doing it is simple and clean. It doesn't require extra boilerplate, it's just using the context that's provided to the widget. 

It seems to me that what you don't like the fact `go_router` needs the context. The context tells the widget where it is in the Element tree. And the reason it needs this is that it can go up the tree to find the widget that holds the navigation capabilities it needs. 

The reason `NavigationAction` can do away with it is that you have to inject the navigator, and this assumes there is a single navigator. In other words, it breaks if you need to have more than one navigator in your app. This means that the use of the provided `NavigationAction` is limited to this very specific case. Something similar with `go_router` would mean that it would also be very limited.

Here is how you can do it yourself: Create a `NavigationGoRouterAction` with a `static BuildContext context` class variable, and then make sure to inject some context from a suitable widget (one close to the top of the tree, that GoRouter can use). An alternative is adding a `static GlobalKey myKey` to this suitable widget, and then the action can get the widget context through that key: `myKey.currentContext`.

Then, your `NavigationGoRouterAction` can just use this context.

**Comment by R4dix** [comment]
Thanks for your reply Marc. I stay with the simple use of the context 👍
