### ISSUE TITLE
undo/redo in async_redux

### ISSUE THREAD

**Issue by JostSchenck** [marcglasberg/async_redux#141]
Is there a solution for an undo/redo stack that goes well with async_redux? Like replay_bloc or replay_riverpod?

**Comment by marcglasberg** [comment]
No, but it's very easy for you to build one yourself in 10 minutes. When you create the `store` you can add a state-observer (see the docs). Just add all states you get from there to a list. When you want to recover one of the states, simple call an action called `RecoverStateAction`, like so:

```
class RecoverStateAction extends ReduxAction<AppState> {
   final AppState recoveredState;

   RecoverStateAction(this.recoveredState);

  @override
  AppState reduce() => recoveredState;
}
```

**Comment by JostSchenck** [comment]
Thank you!

Marcelo Glasberg ***@***.***> schrieb am Di., 4. Okt. 2022,
20:46:
