### ISSUE TITLE
Question regarding action dispatch 

### ISSUE THREAD

**Issue by huvi8161** [marcglasberg/async_redux#143]
I have a question regarding action dispatch, is there an issue with using store global variable to dispatch actions instead of StoreProvider, sometimes we get error's probably because widget is no longer on the stack so his context is not valid, this is probably due to some delay from native code used in that widget. 

`Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Error: No StoreProvider<AppState> found. (debug info: Null)    
    
    To fix, please try:
          
  * Dart 2 (required) 
  * Wrapping your MaterialApp with the StoreProvider<St>, rather than an individual Route
  * Providing full type information to your Store<St>, StoreProvider<St> and StoreConnector<St, Model>
  * Ensure you are using consistent and complete imports. E.g. always use `import 'package:my_app/app_state.dart';
      . Error thrown  Caught error: Error: No StoreProvider<AppState> found. (debug info: Null)    
    
    To fix, please try:
          
  * Dart 2 (required) 
  * Wrapping your MaterialApp with the StoreProvider<St>, rather than an individual Route
  * Providing full type information to your Store<St>, StoreProvider<St> and StoreConnector<St, Model>
  * Ensure you are using consistent and complete imports. E.g. always use `import 'package:my_app/app_state.dart';
      
 Stack trace: #0      StoreProvider.of (package:async_redux/src/store_provider.dart:29)
#1      StoreProvider.dispatch (package:async_redux/src/store_provider.dart:44)
`

**Comment by marcglasberg** [comment]
The `dispatch` method does not depend on the `context` in any way. If you have a reference to your store you can simply do `store.dispatch(SomeAction)`.

The above error can only be thrown when a widget containing a `StoreConnector` is being build. It tries to read the state from the `StoreProvider` up in the tree. It's saying it hasn't found the `StoreProvider`.

Have you followed the examples exactly? 

In any case, you haven't given me enough information to solve this. If you want my help I'd ask you to please create a small runnable example, as simple as possible, self-container, with main method an all, that I can run here on my machine to see the problem.

**Comment by huvi8161** [comment]
The thing is that we are using StoreProvider.of because from the documentation it seam that that was the correct way, but know looking at the documentation more, we think that we can just replace StoreProvider.of with global store variable or even move our callbacks to ViewFactory and use the store provided there. We can't reproduce this error because it is happening only in production on Firebase but probably it is happening because the widget is not active anymore. 

Anyway thanks war the confirmation that dispatch doesn't depend on context I think that is enough, and my congratulations on an excellent redux plugin.
