### ISSUE TITLE
Support connectivity_plus 6.x

### ISSUE THREAD

**Issue by kuhnroyal** [marcglasberg/async_redux#153]
The version has a breaking change with which it now supports multiple connectivity results.

While I like the general idea of the new connectivity check in async_redux, this also introduces a hard dependency. I wonder if it would be better to publish this as a separate package like `async_redux_connectivity`.

**Comment by marcglasberg** [comment]
It was not supposed to be a breaking change. Could you please explain how
is it breaking for you?

Em qua., 10 de abr. de 2024 07:02, Peter Leibiger ***@***.***>
escreveu:

**Comment by kuhnroyal** [comment]
I am talking about the new version of `connectivity_plus` which contains a breaking release.

**Comment by kuhnroyal** [comment]
This is kind of getting more important every day, since only `connectivity_plus:  ^6.0.1` contains the Apple privacy manifest changes.

**Comment by marcglasberg** [comment]
Sorry, I am travelling and without my laptop. I can solve this next week
when I come back. Meanwhile, can you set a dependency override in your
pubspec.yaml?

Em qui., 18 de abr. de 2024 02:31, Peter Leibiger ***@***.***>
escreveu:

**Comment by kuhnroyal** [comment]
All good, no worries.
The problem is a breaking change, `connectivity_plus` now returns a list of `ConnectivityResult` which leads to compile errors.
Meaning you can have a bluetooth, ethernet and whatever connection at the same time.

**Comment by marcglasberg** [comment]
I see. Ok, next week it will be fixed.


Em sex., 19 de abr. de 2024 08:12, Peter Leibiger ***@***.***>
escreveu:

**Comment by kuhnroyal** [comment]
Thanks so much!

**Comment by kuhnroyal** [comment]
Can you also bump the hooks package when you get a chance? Started using this, really helpful!

**Comment by marcglasberg** [comment]
@kuhnroyal See `flutter_hooks_async_redux: ^2.0.0`
