### ISSUE TITLE
waitCondition - A Timer is still pending even after the widget tree was disposed.

### ISSUE THREAD

**Issue by kuhnroyal** [marcglasberg/async_redux#154]
I am trying to update a bigger app with bunch of golden tests to 22 and I keep running into `A Timer is still pending even after the widget tree was disposed.` errors at the end of tests.

```
Timer (duration: 0:10:00.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#6      Store.waitCondition (package:async_redux/src/store.dart:561:35)
```

There is a `waitCondition` in one of the widgets that does not complete.
It seems that there is some cleanup/dispose missing.

**Comment by marcglasberg** [comment]
A `waitCondition` would only resolve when the state fulfils the condition. It can't know that the widget tree was disposed. Maybe I could create a method to cancel all wait conditions, but you'd have to call it yourself, as this is something that only makes sense in tests. What do you think?

**Comment by kuhnroyal** [comment]
Not sure, I think there needs to be a way to remove them.
The `waitCondition` not resolving seems like a common scenario, does it not?

Pre 22.x I used this from the widget tree in a couple places for awaiting initialization and it was correctly cleaned up if the widget was removed. Now it seems like a leak waiting to happen :)

**Comment by marcglasberg** [comment]
It allows you to specify a timeout, and the default timeout is 10 minutes.

I wonder if that timeout is the `Timer` you are seeing:

```dart
if (timeout >= 0)
        future = completer.future.timeout(
          Duration(milliseconds: timeout),
          onTimeout: () {
            _stateConditionCompleters.remove(condition);
            throw TimeoutException(null, Duration(milliseconds: timeout));
          },
        );
```

Could you please test something for me? Make it zero:

```dart
Store.defaultTimeoutMillis = 0;
```

And then tell me if you still get the same error, please.

**Comment by kuhnroyal** [comment]
Same result:

```
Pending timers:
Timer (duration: 0:00:00.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
```

**Comment by kuhnroyal** [comment]
I can work around this by manually listening to `Store.onChange` and verify the condition manually. This way I can cancel the subscription in the dispose function.

**Comment by kuhnroyal** [comment]
While I stopped using the `waitCondition` in widgets now, I still tested around a little bit.

> `Store.defaultTimeoutMillis = -1;`

This works


This also works, advancing the time by 10 minutes.
`await tester.pump(const Duration(minutes: 10));`


I still think that the behavior is bad and might lead to memory leaks. If a `waitCondition` is not fullfilled, the widget is probably kept around in memory for 10 minutes. So I think this needs some kind of dispose/cancel mechanism.

**Comment by marcglasberg** [comment]
Yes, I can think about providing a dispose mechanism, but the problem is that you'd need to call this dispose mechanism from your widget's dispose method. 

Otherwise how can I know that you disposed of your widget and that you have no more use for the `waitCondition`? It's even entirely possible that in some use case you dispose of the widget while still wanting the `waitCondition` to work. I can't really know.

Suppose `waitCondition` gives you access to a `cancel` callback that you can call from your widget's dispose method. Would that solve the problem for you?

**Comment by marcglasberg** [comment]
Also, when you say `the widget is probably kept around in memory for 10 minutes`, why is that?

Is your wait condition referencing the widget? I'd guess it probably doesn't, which means the widget would be disposed normally from memory.

In other words, if your widget creates a `Timer`, this doesn't prevent the widget to be disposed of.

**Comment by kuhnroyal** [comment]
> Suppose waitCondition gives you access to a cancel callback that you can call from your widget's dispose method. Would that solve the problem for you?

I think that would be the correct approach and would also solve my problem. It can then be handled just like any other subscription.

I was storing the `waitCondition` in the widgets state, so yea, you are probably right and it should get cleaned up, at least if it is set to `null` on dispose.

Can't share the code but I am basically wrapping a `StoreConnector` with some initialization handling if if `onInit` and `shouldUpdateModel` is provided. The `onInit` is dispatched manually and the `shouldUpdateModel` is used as  `waitCondition` to be fulfilled before the `StoreConnector` is created.

This allows to display some init/loading widget to be displayed until the first vm is ready.

**Comment by marcglasberg** [comment]
> This allows to display some init/loading widget to be displayed until the first vm is ready.

I don't think you need `waitCondition` to achieve this. Please read this:

---

# Cannot generate view-model

Sometimes you may not have enough information to generate the view-model.
For example, some information may still be loading, or the state is inconsistent for some reason. 

In that case, your factory can return `null` instead of the `vm`, 
and the connector can return an alternative "placeholder widget".

To do that you'll need to declare the view-model as nullable `ViewModel?` in these 3 places:

* The `StoreConnector`
* The `builder`
* The `fromStore` method. 

Then, check for `null` in the `builder`:

```dart                                     
builder: (BuildContext context, ViewModel? vm) { 
  return (vm == null)
    ? Text("User not logged in")
    : MyHomePage(user: vm.user)
```

This is the complete code:

```dart                               
return StoreConnector<AppState, ViewModel?>( // 1. Nullable here

  vm: () => Factory(this),       
  builder: (BuildContext context, ViewModel? vm) { // 2. Nullable here
    return (vm == null) 
      ? Text("User not logged in")
      : MyHomePage(user: vm.user) 
    ...                         
 
class Factory extends VmFactory<AppState, MyHomePageConnector, ViewModel> {   
  ViewModel? fromStore() { // 3. Nullable here
  return (state.user == null)
    ? null
    : ViewModel(user: state.user) 
  ...
```         

Try running
the: <a href="https://github.com/marcglasberg/async_redux/blob/master/example/lib/main_null_viewmodel.dart">Null ViewModel Example</a>.

**Comment by kuhnroyal** [comment]
Yea I read this a while ago but forgot :)
You are right, I might be able to refactor this.

In any case, from my side I can close the issue. I have a way that works atm. with `onStoreChange` and will see about refactoring.
