### ISSUE TITLE
error in docs

### ISSUE THREAD

**Issue by simonkenyongithub** [marcglasberg/async_redux#160]
in the documentation (https://pub.dev/packages/async_redux#giving-better-error-messages) the code:
`
class LogoutAction extends ReduxAction<AppState> {

  @override
  Future<AppState> reduce() async { ... }

  @override
  Object wrapError(error)
	  => LogoutError("Logout failed.", cause: error);
}`

is incorrect. the wrapError has a second parameter.

**Comment by marcglasberg** [comment]
Thank you! (it used to have a single param in the past).

**Comment by marcglasberg** [comment]
Thank you! 

It used to have a single param in the past. This is fixed in our new website: asyncredux.com
