### ISSUE TITLE
Error handling in a persistor

### ISSUE THREAD

**Issue by dropik** [marcglasberg/async_redux#162]
I have a question. How should we handle exceptions in a persistor? Say I want to persist the state to a cloud, or to a remote database, etc. and the connection drops. How would persistor behave in this case? Will it retry the attempt to store the state? Or if not, can we dispatch a PersistAction manually when an exception occurs? And if we do this, will we create race conditions, when old changes are not persisted yet, but new changes already arrive?

**Comment by marcglasberg** [comment]
What I do in my own code is that, if the persistence fails, I assume the saved data is corrupt. I then delete it from the local device, and download it again from the server. But this is when you are using the persistor to save it locally, to the device disk.

If you are using it to synchronize with the cloud, that's different. Even having the phone in airplane mode will make it fail. I think the persistor is not currently prepared to recover from saving failures. I see 2 alternatives:

* Don't fail. In other words, if your persistor fails, catch the exception internally in your save code. Then set some timer and keep retrying, without ever returning from the save Future, until you succeed saving it. The persistor keeps locked and waiting until you return from the save Future, so you will not have race conditions. 

* Let it fail. In this case I must implement calling the persistence again (retrying) after the throttling period (or when you call `PersistAction`). And in this case, the `previousState` should not be updated (otherwise it would not be a retry, right?).

What do you think?

Note: You never get race conditions by calling `PersistAction`, as it only has effects after any current save processes are finished. Just make sure you only return from the save Future when the save is really finished.

**Comment by dropik** [comment]
Thank you for the detailed answer!

I see, so basically the next save call will never be called if previous save is not finished (waiting for save / error handling / whatever). And hence I could implement retry attempts inside there. But more I'm thinking about this, more it seems like this might not be the right solution at least in my case.

The thing is that I do also need to store data locally on device. And the initial idea was to have a decorated persistor. The base persistor stores data to device. While a cloud decoration persistor syncs data with the cloud. The intent here was to let users to save data locally without waiting the response from the server (which is actually more like an optimistic update). But this will not work, since that would mean, that in a single save call I would need to wait as for local data save, as for data upload to cloud. Which then makes no sense to have local data at all.

But even worse. Assume we have retry attempts here, and a logical error occurs when storing to the cloud, which will continue to happen, until I will apply a fix to the cloud system. If the app continues to retry the upload it will 1. not save data to the cloud, but 2. not save subsequent state changes locally. So any eventual changes after the error occured will be lost.

So, speaking of retry attempts, in any case it would be needed to implement at least any error handling in the persistor, to separate logical errors returned from cloud (4xx, 5xx responses) and transient errors (509, connection lost, etc.), and to not retry ones, while attempt to retry others. Which in the end must be handled completely in the save function of the persistor, and so I guess retry automatically as you propose would not be needed.

And for my case, I would need to separate somehow the two persistors completely. Or better saying to handle local data storage inside a persistor, while handling cloud sync not with a persistor at all, but in a separate widget I guess. Which will upload data to cloud, but also synchronise changes occured on server and import them into the app.

**Comment by marcglasberg** [comment]
I could create two separate persistors, one to persist data locally, called `persistor`, and the other maybe called `synchronizer` to sync data to the cloud. What do you think?

**Comment by dropik** [comment]
Okay, this might be an idea. In that case, what do you think about how it would work on downloading changes from the cloud? Because, if I understand it right, current implementation of persistor loads data and creates the state only once during the startup of the app, right? For cloud sync it would be required to not only upload changes to the cloud, but also to do some sort of long polling to retreive any changes from the cloud during the app is running.

**Comment by marcglasberg** [comment]
Yes, a `synchronizer` that's like a persistor would only be part of what's necessary to create cloud sync. You also need to do polling (with a `Timer`) or websockets (with a `Stream`), and then call actions to modify the state. Read this:

https://asyncredux.com/flutter/miscellaneous/streams-and-timers

Whenever information is received from the server via polling or websockets, you call some action that changes the current state. The `persistor` then automatically picks up those changes from the state to save them locally.

**Comment by dropik** [comment]
Okay, this might be a solution I think. Thank you so much for the change! In next days I'll try to test it and tell you the results.

**Comment by dropik** [comment]
So, I've tried to test your solution, but unfortunately there is a problem with it. If cloud sync did not finish with storing data in the cloud, due to low connectivity or whatever, and the app exits, the cloud sync would not retry storing data once again, when app is launched again. But the problem is also, that even if I call the `PersistAction` on app start, the previous state would be lost, and there would be no way to deduce differences between states to persist them.

In that case I would need to keep a list of all entity changes in the state, and when cloud sync save method is called, it would simply look for those changes and would try to store exactly them. But here is another problem, because something should also clear those changes, once they are stored, and this can not be done from a persistor, because it cannot alter the state.

Which makes me think, that may be persistor is not the right place for what I'm trying to achieve either. May be it's just better to place all the thing into an action, and plug it to timer, similarly as you suggested, but for persisting data as well. In this manner I would be able to track changes, attempt to store them in the cloud periodically, be sure that if I relaunch the app and some state was not persisted previously, it would be reattempted to persist, and from the same action I can clear already stored changes.

What do you think about that solution?

**Comment by marcglasberg** [comment]
Well, cloud sync is a complex topic, and it's unlikely I can help you more than the simple tips and ideas above. Keep in mind you can also try adding state observers to the `Store` constructor, where you can have access to all state changes, and maybe implement your solution from there, too. 

I will close this issue, but feel free to ask for more information in case you need it. Good luck!

**Comment by dropik** [comment]
It is complex indeed. I was thinking of the state observers as well, but in the end the problem remains the same. In case of app crash/exit before state is persisted, the fact of the state change itself is lost. So all possible solutions can not work unless I persist that fact somewhere.

Anyway, I think I was able to handle the thing with an action. It both syncs data and persists data to the cloud. Which decides what to persist based on a sort of a track of changes. Works as I was expecting, and the app is able to function offline and re-sync the state once it is back online as well. The only caveat was to not overwrite the state with an old copy of the state, in case more changes in the app occured during async calls to the cloud. So basically I do all the async stuff first, and only after calculate the new state.

So I think I will proceed like this, and thank you for your help!

**Comment by marcglasberg** [comment]
> In case of app crash/exit before state is persisted, the fact of the state change itself is lost.

You would need to save the cloud state(s) to the local device, so that you can retrieve them if the app crashes/exits. Anyway, glad you found another way.

**Comment by dropik** [comment]
Yes, that's what I meant. So the changes are the part of the state and are stored to the local device as well.
