### ISSUE TITLE
Broken link in flutter docs

### ISSUE THREAD

**Issue by DaanDL** [marcglasberg/async_redux#164]
On this page:
https://asyncredux.com/flutter/miscellaneous/advanced-waiting/

There's mention of this url:
https://asyncredux.com/flutter/miscellaneous/basics/wait-fail-succeed

Which doesn't work. The correct url should be:
https://asyncredux.com/flutter/basics/wait-fail-succeed

**Comment by marcglasberg** [comment]
Thank you for letting me know. I will fix this.

**Comment by marcglasberg** [comment]
Fixed.
