### ISSUE TITLE
ignoreChange is named confusingly

### ISSUE THREAD

**Issue by knaeckeKami** [marcglasberg/async_redux#17]
I think, the `ignoreChange` parameter of StoreConnector is named confusingly.
Imagine this example:
``` 
Widget build(BuildContext context) {
    return StoreConnector<AppState, Model>(
      model: Model(),
      ignoreChange: (state) => true,
      builder: (context, model) => Container(),
    );
  }

```

My intuitive understanding of this code would be, that since ignoreChange() evaluates to true, all changes to the state are ignored and the child is never rebuilt due to a change in the app state. 
However, as the documentation correctly states:

`To ignore a change, provide a function that returns true or false. If the returned value is false, the change will be ignored.`, meaning that ignoreChange needs to return false in order to ignore changes.

It might be worth it, now that this library is still pretty new, to rename this parameter to something like "shouldUpdateModel" and to deprecate ignoreChange.

**Comment by marcglasberg** [comment]
I agree with your intuitive understanding. This code is not mine, it's from the original flutter_redux. There's a lot there which I personally never used, but I kept because it's probably useful to others.

To help migrations maybe we can keep that returning false the change will be ignored. How about "rebuildIfModelChanges"?

**Comment by knaeckeKami** [comment]
Well, `rebuildIfModelChanges` would not be really accurate in my opinion.
It might be good the highlight the contrast between `rebuildOnChange` and the current `ignoreChange`parameter.

If `rebuildOnChange` is set to false, the child of StoreConnector will not be rebuilt if the viewmodel changes, but if the Widget needs to be rebuilt for other reasons (e.q. orientation changes), it will still be rebuilt with the newest ViewModel.
However, with ignoreChange, the ViewModel will not be updated and you can build the child with an old ViewModel.

My use case for this is that I remove some data from the AppState when the user navigates away from a screen, but I still want to show this screen for the exit animation, but since I cannot build a useful ViewModel from the appstate any more, I want to stop to ViewModel from being updated for the duration of the transition. 
The Widget is still rebuilt, but with the old ViewModel.

**Comment by marcglasberg** [comment]
Makes sense. I was thinking about "freezeModel". But you would have to return true to ignore changes. To keep ignoring changes on false "shouldUpdateModel" would be better.

**Comment by knaeckeKami** [comment]
Both are fine for me. I only need this in one place currently and don't mind adding or removing when renaming the paraemeter "!" ;).

**Comment by marcglasberg** [comment]
Done. See version: 1.3.8.
