### ISSUE TITLE
SubState clarification

### ISSUE THREAD

**Issue by cgestes** [marcglasberg/async_redux#24]
Hi,

thanks for async_redux it rocks!
I'am currently playing with it and I have some questions.

In https://pub.dev/packages/async_redux#state-declaration you propose to split the state in multiple classes. (like we would do in Redux).

I wonder what to do with actions, should they still inherit from ReduxAction<AppState> and have some kind of nested copy for the reducer like in the following example:

```
class AddTodoAction extends ReduxAction<AppState> {
  final Todo todo;

  AddTodoAction(this.todo);

  @override
  AppState reduce() {
    return state.copy(todos: state.todos.copy(todos: todos.add(todo)));
  }
}
```

Is there a way to avoid cascading the copies?
Also is the copy of the AppState needed when a substate changes, looks like the operator== and the hashCode would detect the change anyway.

Thank you :)

**Comment by marcglasberg** [comment]
Sure, there is a way to avoid cascading the copies. Keep reading:

You may do is creating more specialized abstract actions, that modify only some part of the state. For example:

```
abstract class TodoAction extends ReduxAction<AppState> {
  
  TodoState reduceTodoState();
      
  @override
  AppState reduce() {
    TodoState todoState = reduceTodoState();  
    return (todoState == null) ? null : state.copy(todoState: todoState);
  }
}
```

If you declare those specialized abstract actions, you can have specialized reducers that only need to return that part of the state that changed:

```
class AddTodoAction extends TodoAction {
  final Todo todo;
  AddTodoAction(this.todo);

  @override
  TodoState reduceTodoState() {
    if (todo == null) return null;
    else return List.of(todos)..add(todo);
  }
}
```

**Comment by marcglasberg** [comment]
Regarding your second question, yes, you must copy the state because the state must be immutable. So you can't change it, and you must make a copy with the changes you need.

Now, you may ask **why** it needs to be immutable: https://stackoverflow.com/questions/34958775/why-should-objects-in-redux-be-immutable

But immutablity doesn't need to be hard. This package may help: https://medium.com/flutter-community/kt-dart-better-collections-for-your-flutter-business-logic-41886ab7883

**Comment by cgestes** [comment]
Ok thanks. Nice trick with the abstract class.

**Comment by cgestes** [comment]
Btw.. I just discovered this was in the documentation, maybe it could benefit from a mention closer to state declaration paragraph? I didn't see it as it was mixed with state accessors that I wasn't interested in.

**Comment by kkizlaitis** [comment]
Thank goodness I found this answer! Can confirm, needs more clarity in documentation, @marcglasberg !

By the way, thanks for this great package!
