### ISSUE TITLE
[Bug] getCurrentNavigatorRouteStack only returns first route

### ISSUE THREAD

**Issue by gadfly361** [marcglasberg/async_redux#27]
I was working on a PR to add tests for `NavigateAction`, and I think I discovered a bug in  `getCurrentNavigatorRouteStack`.

https://github.com/marcglasberg/async_redux/blob/6000feeb1c1fb25e93a483c6a3add29abbea0251/lib/src/navigate_action.dart#L30-L38

If I understand the code above correctly, it will pop the *first* route off the stack, and then return `true` ... which effectively cancels the pop.

This means that only the *first* route will be added to the `getCurrentNavigatorRouteStack`. So if you have a navigator route stack with a depth of say 5, `getCurrentNavigatorRouteStack` will only return the first route from the stack and _not_ the whole thing.

If desired, I can produce a minimal example, just let me know.

**Comment by marcglasberg** [comment]
Yes, this makes no sense and I'll remove it. That's what happens when you don't have tests, right? https://www.youtube.com/watch?v=SrDSqODtEFM

**Comment by gadfly361** [comment]
Hahah happens to me all the time 😬
