### ISSUE TITLE
bug: BaseModel.equals is not working for List

### ISSUE THREAD

**Issue by PoiScript** [marcglasberg/async_redux#34]
`BaseModel.equals` uses `listEquals` to compare the properties from two models, but it's kind of broken if one of the properties is a `List`:

```dart
import 'package:async_redux/async_redux.dart';

class ViewModel extends BaseModel<List<int>> {
  List<int> list;

  ViewModel(this.list) : super(equals: [list]);

  @override
  BaseModel fromStore() {
    return ViewModel(state);
  }
}

main() {
  // [1]
  final vm1 = ViewModel([1]);
  // [2]
  final vm2 = (vm1..list[0] = 2);

  // assertion failed
  assert(vm1 != vm2);
}
```

**Comment by marcglasberg** [comment]
You are mutating the original list, not creating a new one. So your vm1 and vm2 are the same and the asserting fails, as it should.

Try this:

    final vm1 = ViewModel([1]);
    final vm2 = ViewModel([2]);
    final vm3 = ViewModel([2]);
    assert(vm1 != vm2);
    assert(vm2 != vm3);

**Comment by PoiScript** [comment]
Thanks for your answer. Actually I am getting a little bit confused. Even though they're the same object, they're containing different values. We can still override the `==` operator to know if this viewmodel is updated or not. I'm not quite sure but creating a new object every time seems to be a performance cost.

**Comment by marcglasberg** [comment]
No, if they are the same object then by definition they contain the same values. They can only contain different values if they are different objects of the same type. This is a Dart issue, not related to Redux. If you make `v2 = v1` you are not creating a new object. You are just pointing two variables to the same object. See this:

    var x = [];
    var y = [];
    x.add("hello")
    assert(y.isEmpty); // Is true.

Now see this:

    var x = [];
    vay y = x;
    x.add("hello")
    assert(y.isEmpty); // Is false.

Maybe this will help you understand: https://www.mathwarehouse.com/programming/passing-by-value-vs-by-reference-visual-explanation.php#:~:targetText=The%20terms%20%22pass%20by%20value,where%20the%20value%20is%20stored

About creating a new object every time, don't worry with that. The performance cost will be negligible, unless you have to do expensive state searches (in which case you can use https://pub.dev/packages/reselect).

**Comment by PoiScript** [comment]
Thanks you for detailed response. I'm still new to dart and very surprised to know that in dart objects are always passed by their references. So it makes sense to create a new object every single time because there're no way to "save" the previous value. After all, thanks again, you're the best. :)
