### ISSUE TITLE
What's the recommend place to manage business logic from

### ISSUE THREAD

**Issue by AhmedMozaly** [marcglasberg/async_redux#37]
Current implementation introduces two places that can hold business logic

ViewModel functions, like `onIncrement` in this example
```
class ViewModel extends BaseModel<AppState> {
  ViewModel();

  int counter;
  String description;
  VoidCallback onIncrement;

  ViewModel.build({
	@required this.counter,
	@required this.description,
	@required this.onIncrement,
  }) : super(equals: [counter, description]);

  @override
  ViewModel fromStore() => ViewModel.build(
		counter: state.counter,
		description: state.description,
		onIncrement: () => dispatch(IncrementAndGetDescriptionAction()),
	  );
}
```

And Action functions, like `reduce` in this example
```
class IncrementAndGetDescriptionAction extends ReduxAction<AppState> {

  @override
  Future<AppState> reduce() async {
	dispatch(IncrementAction());
	String description = await read("http://numbersapi.com/${state.counter}");
	return state.copy(description: description);
  }

  void before() => dispatch(WaitAction(true));

  void after() => dispatch(WaitAction(false));
}
```
In **async_redux** What is the recommend place to manage business logic from?
And by business logic, I mean something like

```
if(isDataExpired){
   // get new data from some web api
}
else if(IsUserNotLoggedIn){
  // route user to login screen
}else{
 // do whatever we need to do
}
```

**Comment by marcglasberg** [comment]
Widgets, Connectors and ViewModels are part of the **client**. They should be in the client module, which is NOT visible by the business module.

Actions, reducers and state classes are part of the **business**. They should be in the business module, which is visible by the client module.

* Don't put your business login in the widgets.
* Don't put your business login in the Connectors.
* Don't put your business login in the ViewModels of the Connectors.
* Put your business login in the Action reducers. 
* Put your business login in the State classes.

**Comment by AhmedMozaly** [comment]
@marcglasberg I think such guidance about where to put business logic is vital info to have in the docs
What do you think?

**Comment by marcglasberg** [comment]
Done. version: 2.3.1.
