### ISSUE TITLE
Cancelable Actions

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [marcglasberg/async_redux#38]
Is there a recommended way to make an async Action cancelable?

This is a "Best Practice" question since I am very unexperienced with redux.

I am doing http requests and the user may cancel them. For this my http client takes an additional parameter "CancelToken".

I create a CancelToken before I dispatch the action that starts the http request. Then I can cancel the http request by calling cancelToken.cancel().

Now, I have to somehow make the cancel token available to the Cancel button, and I guess the only way is through the store, correct? But a cancel token is not a simple data object, but a complex object. Is it still ok to put it in the store?

Is there a recommended way of making Actions cancelable?

Thanks!

**Comment by marcglasberg** [comment]
It depends. You can put them in the store if you want, but I wouldn't do that. This cancel token is probably not persisted, it's probably not immutable, it's probably not used to build widgets with, and probably you don't want to observe changes in it to rebuild widgets when it changes. 

So you can just put it anywhere you want. I would put it in a static variable of the Action itself (And I'd use a Map if there's more than one of these tokens in a given time). Or if you use some DAO to make your http request you could put it inside of your DAO class. Or you can use something like get_it (https://pub.dev/packages/get_it).

**Comment by marcglasberg** [comment]
@RudolfVonKrugstein Also, have a look at this link:

   https://pub.dev/packages/async_redux#where-the-stream-subscriptions-themselves-are-stored

All that it says about streams apply to your use case as well.
