### ISSUE TITLE
Bug: StoreConnector shouldUpdateModel

### ISSUE THREAD

**Issue by raphFlash** [marcglasberg/async_redux#43]
In the StoreConnector, the documentation of the shouldUpdateModel model says : 

> To ignore a change, provide a function that returns true or false. If the returned value is false, the change will be ignored

But the view is rebuilt when the returned value is false and ignored when the value is true.

I guess the problem is here in the _StoreStreamListener 

> if (widget.shouldUpdateModel != null) {
      _stream = _stream.where((state) => !widget.shouldUpdateModel(state));
    }

**Comment by marcglasberg** [comment]
You are absolutely right. Please upgrade to version 2.5.0 for the fix. Thanks.
