### ISSUE TITLE
NavigateAction.pushNamedAndRemoveUntil

### ISSUE THREAD

**Issue by raphFlash** [marcglasberg/async_redux#45]
I would like to do a pushNamedAndRemoveUntil but the NavigateAction only have pushNamedAndRemoveAll method.

I think the NavigateAction should mirror the Navigator possibilities and have a pushNamedAndRemoveUntil method.

**Comment by raphFlash** [comment]
I know that i can do `NavigateAction.navigatorKey.currentState.pushNamedAndRemoveUntil()` but why having the other methods and not this one.

**Comment by marcglasberg** [comment]
See version 2.5.1.
