### ISSUE TITLE
Clarifications in README

### ISSUE THREAD

**Issue by avioli** [marcglasberg/async_redux#48]
It would be great if there is a link to the **State Declaration** section at the top **Store and State** section. Took me a bit to figure out that the AppState is described further down.

Both `listEquals` and `ListEquality` in the **State Declaration** section are unknowns, although I figured that the former comes from `import 'package:flutter/foundation.dart';` and the latter from `import 'package:collection/collection.dart';`.

There may be more tiny bits like these, but I only stumbled upon these so far.

Would you prefer a PR?

**Comment by marcglasberg** [comment]
A PR would be great, for sure!

**Comment by marcglasberg** [comment]
Done: version 2.5.5.
