### ISSUE TITLE
Does this include StateLogger?

### ISSUE THREAD

**Issue by tmclouisluk** [marcglasberg/async_redux#49]
In Logging section of document, it has mentioned we can track the states by using a StateLogger() method.
```
var store = Store<AppState>(
  initialState: state,
  actionObservers: [Log.printer(formatter: Log.verySimpleFormatter)],
  stateObservers: [StateLogger()],  // This
);

```
However, when I use this, it seems cannot find this method in the package.
Do I need to create one myself or can find in somewhere?

**Comment by marcglasberg** [comment]
Sorry if the docs are not clear. The `StateLogger` class is not provided. I'm just saying you _could_ implement such a class as a state observer, not that I'm providing one. I'll update the docs to better reflect that. Thank you.
