### ISSUE TITLE
Roadmap Question

### ISSUE THREAD

**Issue by doc-rj-celltrak** [marcglasberg/async_redux#50]
Hi, I'm new to Redux but this package looks very nice, so thank you! I have a question about plans for enhancements. One thing this package doesn't seem to support is redux_dev_tools and flutter_redux_dev_tools, since they require replacing the store with a dev store for "time travel" for purposes of development and testing. As I said, I'm new to Redux but that dev feature sounds very compelling and Redux architecture in general seems like a great fit for it. Do you have any plans to support "time travel" in this library? No worries if not, but if so, I think it would be yet another benefit of using this package. Having said that, I could be wrong. Maybe "time travel" isn't used very often at all by Redux devs? Thanks in advance for your thoughts on this, and thanks for the awesome library.

**Comment by marcglasberg** [comment]
I never really saw someone using Redux time travel in the wild. It seems to me more like something to demonstrate the immutable state single-store concept. But, I could be wrong.

In any case you can do time-travel with AsyncRedux already. Just create a state-observer (pass it in the store constructor) and save every state to a list. Or to a map indexed by a timestamp. You can then inspect any state, or go back to any state you want. 

But testing should not be done like this. AsyncRedux does have advanced testing capabilities. Please have a look at the `StoreTester` class. It does save state changes and lets you check whatever changes you need.

**Comment by doc-rj-celltrak** [comment]
Thanks @marcglasberg for your response. That sounds good and I do agree that "time travel" shouldn't be used for testing.  I guess it's more often used for replaying/reproducing issues and debugging them. Anyhow, thanks and we will be using your library.
