### ISSUE TITLE
Error in documentation with BaseModel parametrization

### ISSUE THREAD

**Issue by Pitazzo** [marcglasberg/async_redux#58]
Hey there and thanks for this awesome plugin.
I noticed there is an error in section `How to provide the ViewModel to the StoreConnector` in the main documentation. In the example there, it's stated that `BaseModel` class should be parametrized with `BaseModel<Store<AppState>>`. However, in all the other examples its stated that `BaseModel<AppState>` should be used instead, what actually works.
Nothing too serious but it took me a while to realize why VSCode was complaining about it.

**Comment by marcglasberg** [comment]
Fixed. Thanks!
