### ISSUE TITLE
NavigateActions - is it possible to set transition type?

### ISSUE THREAD

**Issue by jans-y** [marcglasberg/async_redux#59]
Hi,

_Firstly – we really love this library and our whole team is using it in every Flutter app we develop. Thank you for your hard work._

**I would like to ask if it's possible to change route transition when using NavigateActions.**

So far I have created custom Action with this code (using **page_transition** library) which works right now:

`navigatorKey.currentState.push(PageTransition(type: PageTransitionType.fade, child: route));`

My goal is to change all routes in my app to have custom transition which I haven't been able to achieve yet in some global setting (no clear documentation on how to do that).

**Thank you.**

**Comment by marcglasberg** [comment]
Please see version 2.5.8 which has the NavigateAction.push(Route) constructor.

I suggest you subclass this action with `class MyNavigateAction extends NavigateAction`, and then your `MyNavigateAction.push` constructor may add the transition you want globally, by calling super.push(PageTransition(type: PageTransitionType.fade, child: route)).

**Comment by jans-y** [comment]
**_Thank you, we really appreciate your work!_** 👏
