### ISSUE TITLE
question - Any similar plugin for React/Angular?

### ISSUE THREAD

**Issue by Pitazzo** [marcglasberg/async_redux#61]
Hey there,
I've been using this plugin for some time and I'm in love with it. I was wondering if the author knows if there is any module for React or Angular which takes advantages of a similar approach to Redux.

Thanks!

**Comment by marcglasberg** [comment]
I believe AsyncRedux could be translated to JavaScript/TypeScript, with adaptations for React or Angular, but as far as I know that's not done at this point. And I also don't know about other Redux versions for React and Angular with a similar approach.
