### ISSUE TITLE
WaitAction with BuiltValue

### ISSUE THREAD

**Issue by raphaelColleau** [marcglasberg/async_redux#64]
Hello,

I like very much the WaitAction because when you have a lot a loading it can pollute you state classes.
But I use BuiltValue for immutability of the State and i think it's a popular choice among dart devs. 
Could you add a way to make it work with BuiltValue ?

Maybe something like this
```
try {
    return (state as dynamic).rebuild((state) => 
        state..wait = state.wait.process(operation, flag: flag, ref: ref));
} catch (_) {
      return (state as dynamic).copy(wait: wait.process(operation, flag: flag, ref: ref));
}
```

**Comment by marcglasberg** [comment]
WIth the help of @knaeckeKami https://github.com/knaeckeKami I have developed a solution that may work for both BuiltValue and Freezed packages, and also lets you inject your own reducer if necessary.

I don't use BuiltValue myself so I can't test it. Could you please test if **version 2.7.1** (in GutHub only, not yet uploaded to pub) works as it should with BuiltValue?

**Comment by raphaelColleau** [comment]
I just tried it and it's working perfectly !
Thanks
