### ISSUE TITLE
Add StackTrace to wrapError and ErrorObserver

### ISSUE THREAD

**Issue by dluksza** [marcglasberg/async_redux#72]
Dart API and syntax is a bit wired when it comes to exceptions. Exception is an object that doesn't include a stack trace information. The stack trace is provided as a second optional parameter in `catch` capsule eg:
```
try {
  throw UserError();
} catch(e, stackTrace) {
  action.wrapError(e, stackTrace);
}
```

Having StackTrace object in wrapError and ErrorObserver interface would enable us to send both to error reporting services like Crashlytics and also make easier to understand the underlying issue.

**Comment by marcglasberg** [comment]
Could you please check if the current version in GitHub (not the one published in pub.dev) solves your issue?

**Comment by dluksza** [comment]
@marcglasberg I've looked at latest commit on `master` and it should solve my issue. Thank you!
