### ISSUE TITLE
Prevent dispatch of certain action types in tests 

### ISSUE THREAD

**Issue by kuhnroyal** [marcglasberg/async_redux#77]
I often have actions that dispatch new actions in `after*` functions, basically chaining a few actions.
When unit testing I always have to mock everything for the whole action chain when I only want to test the first action.
Is there a way to prevent the actual dispatch of these chained action in tests?
StoreTester allows to ignore actions but that is only in regard to their validation.

**Comment by kuhnroyal** [comment]
I found a way by overriding `dispatch*` functions of the Store implementation and checking against an ignore list before calling `super`.
Is this the recommended way?

**Comment by marcglasberg** [comment]
I never really had this problem of ignoring some actions. I guess you found a nice solution.

**Comment by marcglasberg** [comment]
@kuhnroyal 

Just added your idea to AsyncRedux [version 2.12.0], and expanded it so that you can mock actions/reducers, not only disable them. Please have a look:

         https://pub.dev/packages/async_redux#mocking-actions-and-reducers

**Comment by kuhnroyal** [comment]
Thanks @marcglasberg, this is perfect!
