### ISSUE TITLE
_TypeError (type 'NavigateAction<dynamic>' is not a subtype of type 'ReduxAction<AppState>' of 'action'

### ISSUE THREAD

**Issue by oguibueno** [marcglasberg/async_redux#8]
![image](https://user-images.githubusercontent.com/4043166/63699397-9ff64d00-c818-11e9-86b7-47a801c6e247.png)

![image](https://user-images.githubusercontent.com/4043166/63699788-712ca680-c819-11e9-9c48-1573cc6a5f9f.png)

I'm trying to use NavigateAction to redirect to another route, but I'm receiving this error. 

`async_redux: 1.1.2`

**Comment by oguibueno** [comment]
Funcionou! Obrigado!

**Comment by bolein** [comment]
Getting this error on version `2.0.2`

```Dart
StoreProvider.dispatch<AppState>(
                            context,
                            NavigateAction.pop());
```

```
type 'NavigateAction<dynamic>' is not a subtype of type 'ReduxAction<AppState>'
When the exception was thrown, this was the stack: 
#0      StoreProvider.dispatch (package:async_redux/src/store.dart:650:37)
#1      StorySetupPage.build.<anonymous closure> (package:txtstory/story/components/story_setup_page.dart:31:39)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#3      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#4      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
```

Can be fixed by creating `NavigateAction` via the default constructor.

**Comment by marcglasberg** [comment]
@bolein You could also create a parametrized `NavigateAction` via `NavigateAction<AppState>.pop()`

But could you please upgrade to version `2.0.5` and tell me if your original `StoreProvider.dispatch<AppState>(context, NavigateAction.pop());` now works?
