### ISSUE TITLE
Make store available in VmFactory

### ISSUE THREAD

**Issue by kuhnroyal** [marcglasberg/async_redux#93]
I have an old view model using `getAndRemoveFirstError()`.
There is currently no way to access this method when building a `Vm` instance.

I think the store or `getAndRemoveFirstError()` could be added to `VmFactory` to solve this.

**Comment by marcglasberg** [comment]
Sure, no problem. I'll add `getAndRemoveFirstError()`. I don't want to add the `store` because the store state will change, and it's easy to get the wrong one from callbacks.

**Comment by marcglasberg** [comment]
`getAndRemoveFirstError` was already there as a getter, so you should have been able to use it already. I'll change that into a function. I don't want to add the store itself because the store state will change, and it's easy to get the wrong one from callbacks.

**Comment by marcglasberg** [comment]
Could you please test version 6.0.2 ?

**Comment by kuhnroyal** [comment]
You are right I somehow missed that, should work with both versions. Sorry for the noise.
