### ISSUE TITLE
Remove flutter dependency - Create second repository

### ISSUE THREAD

**Issue by stefanschaller** [marcglasberg/async_redux#94]
It would be awesome to have two separate packages. 

`async_redux` → The core functionality 

`asycn_redux_flutter` →  The flutter specific stuff

The goal is, to have the possibility to create a pure dart library that don't have any dependencies to flutter.

Could be similar like:
`redux` → https://pub.dev/packages/redux
`flutter_redux` → https://pub.dev/packages/flutter_redux

Thank you so much, man 🙏🏼

**Comment by marcglasberg** [comment]
Sorry, but this is not something I intend to do. It's best we find a way to separate the code enough so that you can run this package without Flutter when needed. See: https://github.com/marcglasberg/async_redux/issues/90
